version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout # add test steps
      - deploy:
          name: If master, deploy to webserver
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              rsync -va --delete ./caladonis ${WEBSERVER}:${WEBADDRESS}
            fi